/**
 * Egress allowlist builder (BLUEPRINT §3.12.23, THREAT-MODEL B2).
 *
 * Two complementary representations of the same allowlist policy:
 *
 *   1. buildNftablesRuleset  — generates an nft(8) ruleset for uid-scoped
 *      packet filtering on Linux. The ruleset is DEFAULT DROP: every packet
 *      from the given UID is denied unless it matches DNS, established/related
 *      state, or an allowed host on port 443. This is the security-critical
 *      property — the default drop is the final rule in the chain.
 *
 *      Name → IP resolution DOES NOT happen here; it happens at apply time
 *      (e.g. via `nft add element … @allowed_ips { <resolved> }`). This module
 *      only generates the structural ruleset with named-set placeholders and
 *      comments for each host. The generator is pure and macOS-runnable; live
 *      enforcement is Linux-runtime-pending.
 *
 *   2. buildProxyAllowlist — generates an HTTPS-proxy CONNECT allowlist for
 *      environments where packet-level filtering is unavailable. The calling
 *      proxy layer should deny CONNECT to any host not in `allow`.
 *
 * defaultAllowedHosts merges provider API endpoints with the always-required
 * GitHub set so callers get a single source of truth for "what can this UID
 * talk to".
 */

/** GitHub hosts always required for clone/push operations. */
const GITHUB_HOSTS = ["github.com", "api.github.com"] as const;

export interface EgressConfig {
  /** OS uid whose outbound packets are filtered. */
  uid: number;
  /**
   * Hostnames allowed on port 443.
   * e.g. ["api.anthropic.com", "api.openai.com", "github.com", "api.github.com"]
   * IP resolution happens at apply time, not here.
   */
  allowedHosts: string[];
  /** Additional provider API endpoints (merged by defaultAllowedHosts). */
  providerEndpoints?: string[];
}

/**
 * Merge provider-specific endpoints with the mandatory GitHub set.
 * Deduplicates by exact string match; order: GitHub first, then providers.
 */
export function defaultAllowedHosts(providerEndpoints: string[]): string[] {
  const seen = new Set<string>();
  const result: string[] = [];
  for (const h of [...GITHUB_HOSTS, ...providerEndpoints]) {
    if (!seen.has(h)) {
      seen.add(h);
      result.push(h);
    }
  }
  return result;
}

/**
 * Generate an nft(8) ruleset that enforces the allowlist for a single UID.
 *
 * Security-critical properties of the generated ruleset:
 *   - Scoped to `meta skuid <uid>` — only this UID's packets are affected.
 *   - DNS (udp/tcp port 53) is allowed so name resolution works.
 *   - Established/related connections are allowed (stateful tracking).
 *   - Each allowed host gets a named comment and uses a named set
 *     `@allowed_ips_<n>` that MUST be populated with resolved IPs at apply
 *     time before the ruleset is activated.
 *   - DEFAULT DROP is the FINAL rule — anything not explicitly matched is
 *     silently dropped. This is the fail-closed guarantee.
 *
 * The ruleset is returned as a string suitable for `nft -f <file>` on Linux.
 * Do NOT call `nft` here — this function is pure and macOS-runnable.
 */
export function buildNftablesRuleset(cfg: EgressConfig): string {
  const tableName = `nightshift_egress_uid${cfg.uid}`;
  const chainName = "outbound";

  const hostRules = cfg.allowedHosts.map((host, i) => {
    const setName = `allowed_ips_${i}`;
    return [
      `    # host: ${host} — populate set @${setName} with resolved IPs at apply time`,
      `    meta skuid ${cfg.uid} ip daddr @${setName} tcp dport 443 accept`,
    ].join("\n");
  });

  const setDeclarations = cfg.allowedHosts.map((host, i) => {
    const setName = `allowed_ips_${i}`;
    return `  # Resolved IPs for ${host} — populated at apply time\n  set ${setName} {\n    type ipv4_addr\n    flags interval\n  }`;
  });

  const lines: string[] = [
    `# nightshift egress ruleset — uid ${cfg.uid}`,
    `# Generated by src/egress/allowlist.ts. Apply with: nft -f <this-file>`,
    `# Populate each @allowed_ips_N set with resolved IPs before activating.`,
    ``,
    `table inet ${tableName} {`,
    ...setDeclarations,
    ``,
    `  chain ${chainName} {`,
    `    type filter hook output priority 0; policy accept;`,
    ``,
    `    # Only intercept packets from our UID`,
    `    meta skuid != ${cfg.uid} accept`,
    ``,
    `    # Allow DNS so name resolution works`,
    `    meta skuid ${cfg.uid} udp dport 53 accept`,
    `    meta skuid ${cfg.uid} tcp dport 53 accept`,
    ``,
    `    # Allow established/related connections (stateful)`,
    `    meta skuid ${cfg.uid} ct state established,related accept`,
    ``,
    `    # Allow each approved host on port 443`,
    ...hostRules,
    ``,
    `    # DEFAULT DROP — fail-closed: anything not matched above is denied`,
    `    meta skuid ${cfg.uid} drop`,
    `  }`,
    `}`,
  ];

  return lines.join("\n");
}

/**
 * Build an HTTP(S) proxy allowlist as an alternative to packet-level filtering.
 * The proxy layer should deny CONNECT to any hostname not in `allow`.
 */
export function buildProxyAllowlist(cfg: EgressConfig): { allow: string[] } {
  return { allow: [...cfg.allowedHosts] };
}
